#!/bin/bash
#work to do: traps
cr=`echo $'\n> '`
read -p "Do you want to give any compiler arguments? [separate each arg by a space] $cr" compiler_args
trap cleanup 0 1 2 3 15

cleanup()
{
    rm -f ~/temp-progs/"$0"
    rm -f ~/temp-progs/core.*
    rm -f ~/temp-progs/vgcore.*
    rm -f core.*
    rm -f vgcore.*
    exit 0

}
if [ ! -d ~/temp/progs ]; then
`cd ~; mkdir -p temp-progs`
fi
if [ "$0" = "./cinterp" ]; then
echo "You need to make a link to the .c file you want to use this script on..."
echo "use the command ln -s C-interp <name of your .c file> to make a link first and then run the link."
echo "Example: ln -s C-interp foo.c; ./foo <args>"
exit 1
fi
if [ -z "$compiler_args" ]; then
    gcc "$0.c" -O3 -o ~/temp-progs/"$0"
else
    gcc "$0.c" -O3 $compiler_args -o ~/temp-progs/"$0"
fi
~/temp-progs/"$0" "$@"
rm -f ~/temp-progs/"$0"
