#!/bin/bash
cr=`echo $'\n> '`
read -p "What would you like to put in ReadMe? $cr" readme
echo "$readme" >> README.md
git init
git add -A
read -p "What would be your first commit message? $cr" message
git commit -m "$message"
read -p "Please enter the git link to repository $cr" link
if [ "$link" = "" ]; then
git push
echo "Repository created, exiting now..."
exit
fi
git remote add origin $link
echo " If the process prompts you to authenticate, please authenticate "
while true; do
if [[ !$(git push -u origin master)1>/dev/null ]]; then
	echo "Authentication failed, please try again."
else
	echo "Authentication  successful, repo has been successfully created."
	break;
fi
done
