#!/bin/bash

if [ "$#" -eq 0 ]; then
echo "No arguments detected."
echo "Usage: kill_proc <proc name>"
exit -1
fi

procs_to_kill=($(ps -a | grep "$1" | awk '{print $1}'))

for proc in "${procs_to_kill[@]}"; do
    kill -9 "$proc"
done
exit 0