#!/bin/bash

if [ "$#" -eq 0 ]; then
echo "No arguments detected"
echo "Usage: line_changer <line-number> <file> <file> ..."
exit -1
fi

re='^[0-9]+$'
if ! [[ $1 =~ $re ]] ; then
   echo "error: First Argument should be a positive integer" >&2; exit -1
fi

for var in "${@:3}"; do
    if [ ! -f "$var" ]; then
	echo " $var does not exist"
        continue;
    fi
    sed -i "$1s/.*/"$2"/"
done
exit 0
