#!/bin/bash
if [ $# -eq 0 ];then
    echo "No argument detected"
    echo "Usage: runcpp [file.cpp]"
    exit -1
fi
filename=`echo "$1" | sed 's/\.cpp//'`
ln -s ~/Shell-Scripts/cplusplusinterp "$filename"
echo "--------$filename--------"
./"$filename" "${@:2}"
rm -f "$filename"