#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No test source files detected."
    echo "Usage: runjunit TestFile1.java TestFile2.java ..."
    exit -1
fi
file_list=()
for file in "$@"; do
    var=`echo "$file" | sed 's/\.java//'`
    file_list+=($var)
done
javac -cp $JUNIT_JAR:. $@
java -cp $JUNIT_JAR:$HAM_JAR:. org.junit.runner.JUnitCore ${file_list[@]}
rm -rf *.class
