#!/bin/bash
if [ $# -eq 0 ];then
    echo "No argument detected"
    echo "Usage: runcpp [file.java]"
    exit -1
fi
filename=`echo "$1" | sed 's/\.java//'`
ln -s ~/Shell-Scripts/javainterp "$filename"
./"$filename" "${@:2}"
